### ISSUE TITLE
Report data for sites not called as edited?

### ISSUE THREAD

**Issue by AMChalkie** [dieterich-lab/JACUSA#31]
Hi,

It would be really useful to have depth and general information for a site regardless of if it is edited or not. Most importantly for call-1, but also for other modes. 
Why? Because knowing the depth of reads in a position, from a sample with theoretically no editing (a good genetic control), allows "no editing, good read depth" vs "no editing - was it lack of read depth OR lack of editing?"  

Cheers
/Alistair

**Comment by piechottam** [comment]
The problem with showing sites with „no editing“ is to define the set of
„interesting“ sites (limit search space).


Currently, interesting sites for call-1/2 have at least one „variant“ base
call and follow up:

minimal read coverage per BAM file, filtering base call quality,
test-statistic etc.


Restricting to sites with at least one variant base call dramatically
reduces the search space. Otherwise, the entire genome would be written to
the output to preserve sites with no editing because any site not edited
might be interesting.


If you are interested in specific sites with no editing and follow up
question (enough coverage?), I recommend using:


pileup -b <sites-of-interest-no-editing.bed>“

(use the same parameters, you used for your call-1/2: e.g.: minimal
coverage, mapping quality etc.)


and investigate the result to answer:

"no editing, good read depth" vs "no editing - was it lack of read depth OR
lack of editing?"


Am Fr., 17. Mai 2019 um 02:42 Uhr schrieb Alistair Chalk <
notifications@github.com>:

**Comment by AMChalkie** [comment]
Thats fair. However I'm only interested in this for call-1 with a bed file, so a small search space.

**Comment by piechottam** [comment]
For consistency, we decided that call-1/2 (aiming at identifying SNV)
should only output variants.
You can investigate the coverage with "pileup" and a bed file.
You could use the following approach:
1. Given your search space encoded as a bed file S.
2. Identify variants V (should be a subset of S) with JACUSA call-1 -b S.bed
3. V \ S := M is the missing set of your expected variants
4. Run JACUSA pileup -b M.bed
The output contains your coverage information.
Hope that helps.

Am Fr., 17. Mai 2019 um 10:54 Uhr schrieb Alistair Chalk <
notifications@github.com>:
