### ISSUE TITLE
java.lang.Exception: Sequence Dictionaries of BAM files do not match

### ISSUE THREAD

**Issue by kerstinth** [dieterich-lab/JACUSA#39]
Hi, 
I have been trying to use JACUSA using a gDNA bam and cDNA bam file with the command below:

java -jar JACUSA_v1.3.0.jar call-2 -a H:1,B,Y -c 10 -F 1024 -f B -P RF-FIRSTSTRAND,RF-FIRSTSTRAND -p 2 -r rdds_out gDNA.bam cDNA.bam

The RNA is stranded and the DNA is whole exome, both files are sorted, duplicates have been marked and they are indexed.

I have tested it with the example data you provided and it worked but now when using my own data I get the following error:

OutputWriter: rdds_out
[ INFO ] 00:00:00	:	 Computing overlap between sequence records.
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:61)
Caused by: java.lang.Exception: Sequence Dictionaries of BAM files do not match
	at jacusa.method.AbstractMethodFactory.getSAMSequenceRecords(AbstractMethodFactory.java:168)
	at jacusa.method.call.TwoSampleCallFactory.initCoordinateProvider(TwoSampleCallFactory.java:273)
	at jacusa.JACUSA.main(JACUSA.java:238)
	... 5 more

Do you have any suggestions on how this could be resolved?

Best wishes,
Kerstin

**Comment by piechottam** [comment]
Dear kerstinth,

your gDNA.bam and cDNA.bam have different Sequence Dictionaries.
Most likely your cDNA contains "additional" sequences which gDNA does not entail.

samtools view -H <BAM> will give you the header info of a BAM file.

Lines that begin with @SQ are sequence dictionary related.
Example:
[...]
@SQ	SN:1	LN:248956422
@SQ	SN:10	LN:133797422
@SQ	SN:11	LN:135086622
[...]
That would be chromosome(s): 1, 10, and 11

Compare:
samtools view -H gDNA.bam and
samtools view -H cDNA.bam
And decide which header contains all sequences (I assume it will be the cDNA.bam)

Store header:
samtools view -H cDNA.bam > header.sam

Reheader the other BAM file
samtools reheader -P  header.sam gDNA.bam > gDNA_new_header.bam
samtools index gDNA_new_header.bam

Rerun JACUSA
java -jar JACUSA_v1.3.0.jar call-2 -a H:1,B,Y -c 10 -F 1024 -f B -P RF-FIRSTSTRAND,RF-FIRSTSTRAND -p 2 -r rdds_out gDNA_new_header.bam cDNA.bam

Hope that helps.

**Comment by kerstinth** [comment]
Dear Mitschka,

Thank you very much for your help. It worked and Jacusa ran without problems this time.

Best wishes
Kerstin

**Comment by kerstinth** [comment]
Hi again,

I've got one more question. Is reading group information ignored by Jacusa? Otherwise I might have to remove read groups from my files before running Jacusa with re-headed files. I'd be grateful for your input on this. 

Best wishes,
Kerstin

**Comment by piechottam** [comment]
Read Groups are ignored.

**Comment by kerstinth** [comment]
great, thank you!

**Comment by rousselene** [comment]
Hi Kerstinth,
I am trying to use jacusa2 to call variant from a few samples using the reference genome. All my bam files are sorted and indexed.  I cannot get jacusa2 to output vcf files even when I use the -f V parameter. So I let it go on default, but I am only getting a score for the site with variants and not the variant itself.  How do I get jacusa2 to output the score as well as the variants and also frequency > = 0.005?

Thanks in advance

**Comment by piechottam** [comment]
* What happens when you try to use VCF, "Error Message"?
* "[...] but I am only getting a score for the site with variants and not the variant itself" -> What type of output do you expect? This 
* "[...] and also frequency > = 0.005?" -> I recommend to use [JACUSA2helper](https://github.com/dieterich-lab/JACUSA2helper)

**Comment by rousselene** [comment]
> * What happens when you try to use VCF, "Error Message"?
> * "[...] but I am only getting a score for the site with variants and not the variant itself" -> What type of output do you expect? This
> * "[...] and also frequency > = 0.005?" -> I recommend to use [JACUSA2helper](https://github.com/dieterich-lab/JACUSA2helper)

if I try to use -f V command : 
jacusa2 call-1 -p 20 -r 1-1.vcf -R ../reference/Junin_virus_segment_L.fasta -f V -a B,I,Y -q 35 -m 25 -s 1-1_S1.sorted.bam
I got ERROR:
java.lang.IllegalArgumentException: Cannot set a file type if the output is not to a file.
	at htsjdk.variant.variantcontext.writer.VariantContextWriterBuilder.setOutputFileType(VariantContextWriterBuilder.java:185)
	at jacusa.io.format.call.VCFcallWriter.<init>(VCFcallWriter.java:59)
	at jacusa.io.format.call.VCFcallFormat.createWriter(VCFcallFormat.java:41)
	at lib.worker.WorkerDispatcher.<init>(WorkerDispatcher.java:43)
	at lib.util.AbstractMethod.getWorkerDispatcherInstance(AbstractMethod.java:63)
	at lib.util.AbstractTool.run(AbstractTool.java:59)
	at jacusa.JACUSA.main(JACUSA.java:96)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:61)


So right now I am getting the jacusa default output:
#contig start   end     name    score   strand  bases11 info    filter  ref
AY619640.1      5       6       call-1  9.461093298764421       .       0,7,0,0 *       B       A
AY619640.1      7       8       call-1  28.424616659981723      .       0,0,21,0        *       *       T
AY619640.1      9       10      call-1  0.14927238788368413     .       0,0,352,1       *       B       G
AY619640.1      10      11      call-1  0.014412135380553082    .       4337,0,0,1      *       B       A
AY619640.1      11      12      call-1  0.39320193231105804     .       0,7,0,8165      *       B       T
AY619640.1      12      13      call-1  1.5085363055113703      .       0,10267,0,16    *       *       C
AY619640.1      13      14      call-1  0.05748258769745007     .       2,13156,0,2     *       B       C
AY619640.1      14      15      call-1  0.012755364179611206    .       1,0,1,13633     *       *       T

I am guessing if I had a vcf file output jacusa would also output the variant indicating A, T or C,G changes that occur based on the reference genome and the mapped bam files. I am not sure, please let me know.

Also, I am not seeing any frequency filter in the JACUSA2Helper. Can you point me to the right direction? Thanks

**Comment by piechottam** [comment]
(Please resubmit this issue in [JACUSA**2**](https://github.com/dieterich-lab/JACUSA2))

Please have a look at: https://dieterich-lab.github.io/JACUSA2helper/articles/JACUSA2helper.html
The function that you are looking for is: `non_ref_ratio(bases, ref)`
You have to calculate the frequency with the aforementioned method and then apply a filter.

**Comment by rousselene** [comment]
> (Please resubmit this issue in [JACUSA**2**](https://github.com/dieterich-lab/JACUSA2))
> 
> Please have a look at: https://dieterich-lab.github.io/JACUSA2helper/articles/JACUSA2helper.html The function that you are looking for is: `non_ref_ratio(bases, ref)` You have to calculate the frequency with the aforementioned method and then apply a filter.

Thanks for getting back to me.  I give my input file:
> result
# A tibble: 6,991 × 12
   id              contig     start   end name     score strand bases$cond1$rep1$A  $$$C  $$$G  $$$T cov$cond1$rep1 info  filter ref  
   <chr>           <chr>      <int> <int> <chr>    <dbl> <chr>               <dbl> <dbl> <dbl> <dbl>          <dbl> <chr> <chr>  <chr>
 1 AY619640.1:7:.  AY619640.1     7     8 call-1 17.6    .                       0     0    13     0             13 *     *      T    
 2 AY619640.1:11:. AY619640.1    11    12 call-1  0.0129 .                       1     0     0  5213           5214 *     B      T    
 3 AY619640.1:12:. AY619640.1    12    13 call-1  0.0470 .                       1  6848     1     1           6851 *     B      C    
 4 AY619640.1:13:. AY619640.1    13    14 call-1  0.211  .                       4  8972     1     1           8978 *     B      C    
 5 AY619640.1:14:. AY619640.1    14    15 call-1  0.0288 .                       0     2     0  9262           9264 *     *      T    
 6 AY619640.1:16:. AY619640.1    16    17 call-1  0.0184 .                       1     1  9883     0           9885 *     *      G    
 7 AY619640.1:17:. AY619640.1    17    18 call-1  0.0566 .                       3     0 16584     1          16588 *     B      G    
 8 AY619640.1:18:. AY619640.1    18    19 call-1  0.179  .                       0 19114     0     7          19121 *     *      C    
 9 AY619640.1:19:. AY619640.1    19    20 call-1  0.225  .                       6     0 18976     3          18985 *     *      G    
10 AY619640.1:20:. AY619640.1    20    21 call-1  0.0239 .                       2     1     0 19343          19346 *     *      T    
# … with 6,981 more rows

when run JACUSA2helper with the "non_ref_ratio" function I got this error:
> non_ref_ratio(result)
Error in stopifnot(length(ref) == nrow(bases)) : 
  argument "ref" is missing, with no default

is there a reason why ? since I have the "ref" column in my input file I am not sure why the function is not seeing it. Can you help with that?

**Comment by piechottam** [comment]
"non_ref_ratio" works on columns of bases. The correct way to use it would be:
```
non_ref_ratio(result$cond1$rep1, result$ref)
```
This gives you the non-reference ratio for condition 1 replicate 1 against the reference used for mapping.

**Comment by rousselene** [comment]
> "non_ref_ratio" works on columns of bases. The correct way to use it would be:
> 
> ```
> non_ref_ratio(result$cond1$rep1, result$ref)
> ```
> 
> This gives you the non-reference ratio for condition 1 replicate 1 against the reference used for mapping.

can

> non_ref_ratio(result$cond1$rep1, result$ref)

still not working:
> non_ref_ratio(result$cond1$rep1, result$ref)
**Error in rowSums(bases) : 'x' must be an array of at least two dimensions
In addition: Warning message:
Unknown or uninitialised column: `cond1`**

but if I do:
non_ref_ratio(result$bases, result$ref)
it outputs a lot of frequences as result as seen below:
 [1] 1.000000e+00 1.917913e-04 4.378923e-04 6.683003e-04 2.158895e-04 2.023268e-04 2.411382e-04 3.660896e-04 4.740585e-04 1.550708e-04 3.247808e-04
  [12] 2.468933e-04 1.119612e-03 2.915622e-04 2.850221e-04 2.874637e-04 3.299043e-04 2.165381e-04 3.721623e-04 3.030887e-04 2.759174e-04 3.737945e-04
  [23] 2.564030e-04 1.478561e-04 1.703080e-04 2.051984e-04 2.330114e-04 3.169438e-04 1.476139e-04 3.653007e-04 3.588769e-04 3.359439e-04 1.744592e-04
  [34] 3.127280e-04 6.194587e-04 1.875508e-04 5.106657e-03 4.592652e-04 2.328584e-04 3.878675e-04 2.829884e-04 3.198495e-04 1.487652e-04 3.611738e-04
  [45] 1.065511e-04 4.053435e-04 2.805443e-04 3.995414e-04 2.950774e-04 3.362874e-04 3.107975e-04 5.068069e-04 5.841924e-04 3.316442e-03 2.978798e-04


Is there a way to have it output the  same input table with just an added frequency column in it? 

Thanks
